using System;using CapybaraGame.Core;
namespace CapybaraGame.Puzzle{
[Serializable]public sealed class DifficultyProfile{public float gridWeight=.10f,regionComplexityWeight=.15f,candidateWeight=.20f,forcedMoveWeight=.15f,deductionDepthWeight=.15f,backtrackWeight=.10f,ambiguityWeight=.10f,topologyWeight=.05f;public float EasyMax=35f,MediumMax=68f;}
public sealed class DifficultyMetrics{public float Score,AverageCandidates,RegionComplexity,ForcedMoveRatio,DeductionDepth,BacktrackRatio,Ambiguity,TopologyComplexity,EstimatedSolveSeconds;public PuzzleDifficultyBand Band;}
public static class PuzzleDifficultyEvaluator{
public static DifficultyMetrics Evaluate(PuzzleDefinition p,DifficultyProfile profile=null){profile=profile??new DifficultyProfile();var s=PuzzleSolver.Solve(p,2);float avg=AverageCandidates(p);float topo=Topology(p);float complexity=RegionComplexity(p,topo);float forced=p.rows==0?0:(float)s.Metrics.ForcedMoves/p.rows;float depth=p.rows==0?0:(float)s.Metrics.MaximumDepth/p.rows;float back=s.Metrics.NodesVisited==0?0:(float)s.Metrics.Backtracks/s.Metrics.NodesVisited;float amb=Math.Min(1f,avg/Math.Max(1f,p.rows*.65f));float grid=Math.Max(0,Math.Min(1f,(p.rows-4)/3f));float score=100f*(grid*profile.gridWeight+complexity*profile.regionComplexityWeight+(1-Math.Min(1,avg/Math.Max(1,p.rows)))*profile.candidateWeight+(1-Math.Min(1,forced))*profile.forcedMoveWeight+depth*profile.deductionDepthWeight+Math.Min(1,back)*profile.backtrackWeight+amb*profile.ambiguityWeight+topo*profile.topologyWeight);score=Math.Max(0,Math.Min(100,score));return new DifficultyMetrics{Score=score,Band=score<profile.EasyMax?PuzzleDifficultyBand.Easy:score<profile.MediumMax?PuzzleDifficultyBand.Medium:PuzzleDifficultyBand.Hard,AverageCandidates=avg,RegionComplexity=complexity,ForcedMoveRatio=forced,DeductionDepth=depth,BacktrackRatio=back,Ambiguity=amb,TopologyComplexity=topo,EstimatedSolveSeconds=Math.Max(2,3*p.rows+s.Metrics.NodesVisited*.18f+amb*10)};}
static float AverageCandidates(PuzzleDefinition p){var state=new int[p.CellCount];for(int i=0;i<state.Length;i++)state[i]=-1;float total=0;for(int r=0;r<p.rows;r++){int n=0;for(int c=0;c<p.columns;c++)if(PuzzleValidator.IsPlacementValid(p,state,r,c))n++;total+=n;state[r*p.columns+p.solution[r]]=0;}return total/p.rows;}
static float RegionComplexity(PuzzleDefinition p,float topo){var s=new int[p.regionCount];foreach(int z in p.regions)s[z]++;float m=(float)p.CellCount/p.regionCount,v=0;foreach(int x in s){float d=x-m;v+=d*d;}return Math.Min(1f,(float)Math.Sqrt(v/p.regionCount)/Math.Max(1,m)*1.6f+topo*.55f);}
static float Topology(PuzzleDefinition p){int b=0;for(int r=0;r<p.rows;r++)for(int c=0;c<p.columns;c++){int z=p.RegionAt(r,c);if(r+1<p.rows&&p.RegionAt(r+1,c)!=z)b++;if(c+1<p.columns&&p.RegionAt(r,c+1)!=z)b++;}int max=Math.Max(1,2*p.rows*p.columns-p.rows-p.columns);return Math.Min(1f,(float)b/max);}
}}