using System;using System.Collections.Generic;using CapybaraGame.Core;
namespace CapybaraGame.Puzzle{
[Serializable]public sealed class PuzzleGenerationConfig{public int rows=5,columns=5,regionCount=5,seed=1,generationVersion=1,maxAttempts=500;public bool requireUniqueSolution=true,requireConnectedRegions=true;public DifficultyProfile difficultyProfile=new DifficultyProfile();public PuzzleDifficultyBand? targetBand;public PuzzleCategory? category;}
public sealed class PuzzleGenerationResult{public PuzzleDefinition Puzzle;public string FailureReason;public int Attempts;}
public static class PuzzleGenerator{
public static PuzzleGenerationResult Generate(PuzzleGenerationConfig c){Validate(c);string fail="No candidate passed quality filters.";for(int a=0;a<c.maxAttempts;a++){var rng=new DeterministicRandom(Mix(c.seed,c.generationVersion,a));var sol=Solution(c.rows,rng);if(sol==null){fail="Solution generation failed.";continue;}var reg=Regions(c.rows,sol,rng);var p=new PuzzleDefinition{id="GENERATED-"+c.seed,seed=c.seed,rows=c.rows,columns=c.columns,regionCount=c.regionCount,regions=reg,solution=sol,generatorVersion="phase2-v"+c.generationVersion,contentVersion="1",initialState=Empty(c.rows*c.columns)};if(!PuzzleValidator.IsRegionMapValid(p,c.requireConnectedRegions)){fail="Invalid regions.";continue;}var s=PuzzleSolver.Solve(p,2);if(s.SolutionCount==0){fail="No solution.";continue;}if(c.requireUniqueSolution&&s.SolutionCount!=1){fail="Multiple solutions.";continue;}var d=PuzzleDifficultyEvaluator.Evaluate(p,c.difficultyProfile);if(c.targetBand.HasValue&&d.Band!=c.targetBand.Value){fail="Difficulty outside target.";continue;}p.solutionCount=s.SolutionCount;p.difficulty=d.Score;p.difficultyBand=d.Band.ToString();p.category=c.category.HasValue?c.category.Value.ToString():Classify(d);p.fingerprint=PuzzleFingerprint.Compute(p);return new PuzzleGenerationResult{Puzzle=p,Attempts=a+1};}return new PuzzleGenerationResult{FailureReason=fail,Attempts=c.maxAttempts};}
static int[] Solution(int n,DeterministicRandom rng){var s=new int[n];for(int i=0;i<n;i++)s[i]=-1;for(int r=0;r<n;r++){var cs=new List<int>();for(int c=0;c<n;c++){bool ok=true;for(int q=0;q<r;q++)if(s[q]==c||(Math.Abs(q-r)<=1&&Math.Abs(s[q]-c)<=1)){ok=false;break;}if(ok)cs.Add(c);}if(cs.Count==0)return null;s[r]=cs[rng.NextInt(0,cs.Count)];}return s;}
static int[] Regions(int n,int[] sol,DeterministicRandom rng){var a=Empty(n*n);var f=new List<int>[n];for(int i=0;i<n;i++)f[i]=new List<int>();for(int z=0;z<n;z++){int i=z*n+sol[z];a[i]=z;f[z].Add(i);}int left=a.Length-n;while(left>0){var ids=new List<int>();for(int z=0;z<n;z++)if(f[z].Count>0)ids.Add(z);if(ids.Count==0)return null;int z=ids[rng.NextInt(0,ids.Count)],src=f[z][rng.NextInt(0,f[z].Count)],r=src/n,c=src%n;var cs=new List<int>();Add(r-1,c);Add(r+1,c);Add(r,c-1);Add(r,c+1);if(cs.Count==0){f[z].Remove(src);continue;}int pick=cs[rng.NextInt(0,cs.Count)];a[pick]=z;f[z].Add(pick);left--;void Add(int rr,int cc){if(rr>=0&&rr<n&&cc>=0&&cc<n&&a[rr*n+cc]==-1)cs.Add(rr*n+cc);}}return a;}
static string Classify(DifficultyMetrics d){if(d.ForcedMoveRatio>.75f&&d.EstimatedSolveSeconds<35)return PuzzleCategory.QuickSolve.ToString();if(d.RegionComplexity>.65f)return PuzzleCategory.ComplexRegions.ToString();if(d.DeductionDepth>.85f)return PuzzleCategory.DeepLogic.ToString();if(d.Ambiguity>.65f)return PuzzleCategory.Sparse.ToString();if(d.ForcedMoveRatio<.35f)return PuzzleCategory.ChainReaction.ToString();return PuzzleCategory.Balanced.ToString();}
static int[] Empty(int n){var a=new int[n];for(int i=0;i<n;i++)a[i]=-1;return a;}static int Mix(int seed,int version,int attempt){unchecked{uint x=(uint)seed^(uint)version*0x9E3779B9u^(uint)(attempt+1)*0x85EBCA6Bu;x^=x>>16;x*=0x7FEB352Du;x^=x>>15;return(int)x;}}
static void Validate(PuzzleGenerationConfig c){if(c==null)throw new ArgumentNullException(nameof(c));if(c.rows<4||c.rows>7||c.columns!=c.rows||c.regionCount!=c.rows)throw new ArgumentException("Phase 2 requires square 4x4 through 7x7 boards with one region per row.");}}
}